name : PreProcessing dataset
on :
  push :
    branches :
      - main
      - test
jobs :
  preprocess :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout code
        uses : actions/checkout@v3
        
      - name : Preprocess dataset
        run : |
          python preprocess.py