name: Kriteria 3

on:
  push:
    branches:
      - main
      - test

jobs:
 build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train / log model with MLflow
        working-directory: kriteria3/
        run: |
          mlflow run . --env-manager=local 

      - name: Get Run ID
        working-directory: kriteria3/
        run: |
          echo "=== Listing mlruns structure ==="
          ls -la mlruns/ || echo "No mlruns folder"
          ls -la mlruns/0/ || echo "No mlruns/0 folder"
          echo "=== Finding Run ID ==="
          RUN_ID=$(find mlruns/0 -maxdepth 1 -type d -name '[a-f0-9]*' | head -n 1 | xargs basename)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Found Run ID: $RUN_ID"

      - name: Saving model as artifact to github actions
        uses: actions/upload-artifact@v4
        with:
          name: kriteria3-model
          path: kriteria3/mlruns/0/${{ env.RUN_ID }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build model serving image with MLflow 
        working-directory: kriteria3/
        run: |
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "itsam77/kriteria3-model"


      - name: Push Docker image
        run: |
          docker push itsam77/kriteria3-model:latest